import type { Permission } from './constants.js';

export interface ReportDefinition {
  reportId: string;
  reportName: string;
  description: string;
  category:
    | 'overview'
    | 'sales'
    | 'products'
    | 'inventory'
    | 'purchasing'
    | 'financial'
    | 'shifts'
    | 'audit'
    | 'food_service'
    | 'platform';
  module: string;
  version: string;
  status: 'active' | 'beta' | 'premium';
  purpose: string;
  targetUsers: string[];
  businessQuestions: string[];
  metrics: string[];
  dataSources: string[];
  requiredModules: string[];
  requiredCapabilities: Permission[];
  allowedBusinessProfiles: Array<'retail' | 'food_service' | 'hybrid'>;
  availableFilters: string[];
  availableGroupings: string[];
  availableSorting: string[];
  supportedCharts: Array<'kpi' | 'table' | 'line' | 'bar' | 'horizontal_bar' | 'donut' | 'pie' | 'timeline' | 'radial'>;
  supportedExports: Array<'pdf' | 'xlsx' | 'csv'>;
  drillDownPath: string[];
  refreshStrategy: 'real_time' | 'five_minutes' | 'on_demand';
  sensitiveFields: string[];
  defaultDateRange: string;
}

export const REPORT_CATALOG: ReportDefinition[] = [
  {
    reportId: 'sales_overview',
    reportName: 'Dashboard Overview',
    description: 'Executive revenue, transaction, and profitability performance',
    category: 'overview',
    module: 'Reports',
    version: '1.0',
    status: 'active',
    purpose: 'Provide a branch-level operating snapshot using the canonical Ximo metrics.',
    targetUsers: ['Owner', 'Manager', 'Cashier (own activity)', 'Inventory Clerk', 'Purchasing Clerk', 'Auditor'],
    businessQuestions: ['How is the branch performing?', 'What needs attention now?', 'How does this period compare with the selected comparison period?'],
    metrics: ['gross_sales', 'total_discounts', 'refund_amount', 'net_sales', 'transactions', 'average_transaction_value', 'cogs', 'gross_profit', 'profit_margin'],
    dataSources: ['sales', 'sale_items', 'returns', 'return_items', 'payments', 'branch_inventory', 'purchase_orders', 'register_shifts'],
    requiredModules: ['dashboard'],
    requiredCapabilities: ['reports:read'],
    allowedBusinessProfiles: ['retail', 'food_service', 'hybrid'],
    availableFilters: ['dateRange', 'branchId', 'cashierId', 'paymentMethod'],
    availableGroupings: ['day', 'branch', 'category', 'paymentMethod'],
    availableSorting: ['highestRevenue', 'lowestRevenue', 'quantitySold', 'alphabetical'],
    supportedCharts: ['kpi', 'line', 'donut', 'bar', 'table'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Dashboard Overview', 'Report Category', 'Source Records'],
    refreshStrategy: 'real_time',
    sensitiveFields: ['netCost', 'grossProfit', 'grossMarginPercent'],
    defaultDateRange: '30d',
  },
  {
    reportId: 'sales_summary',
    reportName: 'Sales Summary Proof Report',
    description: 'Canonical sales, refund, tax, discount, and alternate-unit performance summary',
    category: 'sales',
    module: 'Sales',
    version: '1.0',
    status: 'active',
    purpose: 'Reconcile gross sales, discounts, refunds, net sales, tax, COGS, and profit for a selected period.',
    targetUsers: ['Owner', 'Manager', 'Cashier (own shift)', 'Auditor'],
    businessQuestions: ['How much did we sell?', 'What reduced gross sales?', 'What is the resulting profit?'],
    metrics: ['gross_sales', 'total_discounts', 'refund_amount', 'net_sales', 'cogs', 'gross_profit', 'profit_margin', 'average_transaction_value', 'average_items_per_transaction'],
    dataSources: ['sales', 'sale_items', 'returns', 'return_items', 'payments'],
    requiredModules: ['dashboard'],
    requiredCapabilities: ['reports:read'],
    allowedBusinessProfiles: ['retail', 'food_service', 'hybrid'],
    availableFilters: ['dateRange', 'branchId'],
    availableGroupings: ['product', 'category', 'branch'],
    availableSorting: ['highestRevenue', 'lowestRevenue', 'quantitySold'],
    supportedCharts: ['kpi', 'line', 'bar', 'table'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Sales Summary', 'Transaction History', 'Transaction Details'],
    refreshStrategy: 'real_time',
    sensitiveFields: ['netCost', 'grossProfit', 'grossMarginPercent'],
    defaultDateRange: '30d',
  },
  {
    reportId: 'product_performance',
    reportName: 'Product Performance',
    description: 'Product sales volume, alternate selling unit breakdowns, and product gross profit',
    category: 'sales',
    module: 'Products',
    version: '1.0',
    status: 'active',
    purpose: 'Measure product sales volume, revenue, cost, profit, and alternate-unit performance.',
    targetUsers: ['Owner', 'Manager', 'Inventory Clerk', 'Purchasing Clerk', 'Auditor'],
    businessQuestions: ['Which products sell the most?', 'Which products generate the most profit?', 'Which selling units are used?'],
    metrics: ['gross_sales', 'inventory_quantity', 'cogs', 'gross_profit', 'profit_margin'],
    dataSources: ['sale_items', 'sales', 'products', 'product_variants', 'categories'],
    requiredModules: ['dashboard'],
    requiredCapabilities: ['reports:read'],
    allowedBusinessProfiles: ['retail', 'food_service', 'hybrid'],
    availableFilters: ['dateRange', 'branchId', 'categoryId'],
    availableGroupings: ['product', 'category', 'sellingUnit'],
    availableSorting: ['highestRevenue', 'lowestRevenue', 'quantitySold', 'alphabetical'],
    supportedCharts: ['kpi', 'bar', 'horizontal_bar', 'donut', 'table'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Product Performance', 'Product', 'Transaction Details'],
    refreshStrategy: 'five_minutes',
    sensitiveFields: ['unitCost', 'netCost', 'grossProfit', 'grossMarginPercent'],
    defaultDateRange: '30d',
  },
  {
    reportId: 'inventory_valuation',
    reportName: 'Inventory Valuation',
    description: 'Stock on hand quantities, low-stock alerts, and stock valuation by branch',
    category: 'inventory',
    module: 'Inventory',
    version: '1.0',
    status: 'active',
    purpose: 'Show on-hand stock, cost and retail valuation, stock risk, movement activity, and turnover.',
    targetUsers: ['Owner', 'Manager', 'Inventory Clerk', 'Purchasing Clerk', 'Auditor'],
    businessQuestions: ['What stock is available?', 'What is inventory worth?', 'Which products are low, out, or inactive?'],
    metrics: ['inventory_value_cost', 'inventory_value_retail', 'inventory_quantity', 'stock_turnover', 'dead_stock'],
    dataSources: ['branch_inventory', 'products', 'categories', 'inventory_movements', 'sale_items', 'sales'],
    requiredModules: ['inventory'],
    requiredCapabilities: ['reports:read'],
    allowedBusinessProfiles: ['retail', 'food_service', 'hybrid'],
    availableFilters: ['branchId', 'categoryId'],
    availableGroupings: ['category', 'branch', 'status'],
    availableSorting: ['highestValue', 'lowestValue', 'quantity', 'alphabetical'],
    supportedCharts: ['kpi', 'radial', 'donut', 'bar', 'table', 'timeline'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Inventory Summary', 'Product Stock', 'Inventory Movement Ledger'],
    refreshStrategy: 'real_time',
    sensitiveFields: ['inventoryValue', 'averageCost'],
    defaultDateRange: 'today',
  },
  {
    reportId: 'purchasing_summary',
    reportName: 'Purchasing & Supplier Payables',
    description: 'Purchase orders, stock receipts, and unpaid supplier invoices',
    category: 'purchasing',
    module: 'Purchasing',
    version: '1.0',
    status: 'active',
    purpose: 'Track purchase commitments, receiving accuracy, supplier fulfillment, returns, payments, and payables.',
    targetUsers: ['Owner', 'Manager', 'Inventory Clerk (receiving)', 'Purchasing Clerk', 'Auditor'],
    businessQuestions: ['How much was ordered and received?', 'Are suppliers fulfilling orders?', 'What remains payable?'],
    metrics: ['purchase_value', 'receiving_accuracy', 'supplier_fulfillment_rate'],
    dataSources: ['purchase_orders', 'purchase_order_items', 'stock_receipts', 'stock_receipt_items', 'purchase_returns', 'supplier_invoices', 'supplier_payments'],
    requiredModules: ['purchasing'],
    requiredCapabilities: ['reports:read', 'purchasing:read'],
    allowedBusinessProfiles: ['retail', 'food_service', 'hybrid'],
    availableFilters: ['dateRange', 'branchId', 'supplierId'],
    availableGroupings: ['supplier', 'status'],
    availableSorting: ['highestValue', 'lowestValue', 'alphabetical', 'status'],
    supportedCharts: ['kpi', 'bar', 'radial', 'table', 'timeline'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Purchasing Summary', 'Purchase Order', 'Receiving / Return / Payment Records'],
    refreshStrategy: 'five_minutes',
    sensitiveFields: ['outstandingPayables', 'orderedValue', 'receivedValue'],
    defaultDateRange: '30d',
  },
  {
    reportId: 'profit_analysis',
    reportName: 'Profit Analysis',
    description: 'Net sales, cost of goods sold, gross profit, and margin performance',
    category: 'financial',
    module: 'Profit & Financial Reports',
    version: '1.0',
    status: 'active',
    purpose: 'Explain how completed sales, discounts, refunds, and cost of goods produce branch gross profit.',
    targetUsers: ['Owner', 'Manager', 'Auditor'],
    businessQuestions: ['How profitable was the selected period?', 'What is the gross margin?', 'How is profit changing over time?'],
    metrics: ['gross_sales', 'total_discounts', 'refund_amount', 'net_sales', 'cogs', 'gross_profit', 'profit_margin'],
    dataSources: ['sales', 'sale_items', 'returns', 'return_items', 'products', 'branch_inventory'],
    requiredModules: ['dashboard'],
    requiredCapabilities: ['reports:read'],
    allowedBusinessProfiles: ['retail', 'food_service', 'hybrid'],
    availableFilters: ['dateRange', 'branchId'],
    availableGroupings: ['day', 'branch', 'product', 'category'],
    availableSorting: ['highestRevenue', 'highestProfit', 'lowestMargin'],
    supportedCharts: ['kpi', 'line', 'bar', 'table'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Profit Analysis', 'Date / Product / Category', 'Source Transactions'],
    refreshStrategy: 'on_demand',
    sensitiveFields: ['netCost', 'grossProfit', 'grossMarginPercent'],
    defaultDateRange: '30d',
  },
  {
    reportId: 'recipe_costing',
    reportName: 'Recipe Cost & Ingredient Usage',
    description: 'Food service recipe cost %, theoretical ingredient usage, and margin',
    category: 'food_service',
    module: 'Production & Repacking',
    version: '1.0',
    status: 'active',
    purpose: 'Measure recipe cost, ingredient usage, production yield, loss, and allocated output cost.',
    targetUsers: ['Owner', 'Manager', 'Inventory Clerk', 'Auditor'],
    businessQuestions: ['What did each batch consume?', 'What yield and loss were recorded?', 'What cost was allocated to each output unit?'],
    metrics: ['yield_percent', 'loss_percent', 'cost_allocation'],
    dataSources: ['production_batches', 'production_batch_items', 'product_recipes', 'inventory_movements'],
    requiredModules: ['recipes'],
    requiredCapabilities: ['reports:read'],
    allowedBusinessProfiles: ['food_service', 'hybrid'],
    availableFilters: ['dateRange', 'branchId'],
    availableGroupings: ['recipe', 'ingredient'],
    availableSorting: ['highestCost', 'lowestYield', 'latest'],
    supportedCharts: ['kpi', 'bar', 'radial', 'table', 'timeline'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Repacking Performance', 'Production Batch', 'Consumed Ingredients'],
    refreshStrategy: 'real_time',
    sensitiveFields: ['recipeCost', 'costPerServing', 'foodCostPercent', 'grossMarginPercent'],
    defaultDateRange: '30d',
  },
  {
    reportId: 'cash_shift_accountability',
    reportName: 'Cash & Shift Accountability',
    description: 'Register opening, movements, expected cash, counted cash, and variance',
    category: 'shifts',
    module: 'Registers & Shifts',
    version: '1.0',
    status: 'active',
    purpose: 'Reconcile each cash drawer and make shift variances auditable.',
    targetUsers: ['Owner', 'Manager', 'Cashier (own shift)', 'Auditor'],
    businessQuestions: ['What should be in the drawer?', 'What was counted?', 'Which shifts have a variance?'],
    metrics: ['cash_variance', 'cash_drawer_balance'],
    dataSources: ['register_shifts', 'cash_movements', 'sales', 'payments', 'returns'],
    requiredModules: ['registers'],
    requiredCapabilities: ['reports:read'],
    allowedBusinessProfiles: ['retail', 'food_service', 'hybrid'],
    availableFilters: ['dateRange', 'branchId', 'cashierId', 'status'],
    availableGroupings: ['cashier', 'register', 'day', 'status'],
    availableSorting: ['latest', 'largestVariance', 'cashier'],
    supportedCharts: ['kpi', 'bar', 'table', 'timeline'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Cash & Shifts', 'Shift', 'Cash Movements / Payments'],
    refreshStrategy: 'real_time',
    sensitiveFields: ['expectedCash', 'countedCash', 'variance'],
    defaultDateRange: 'today',
  },
  {
    reportId: 'audit_activity',
    reportName: 'Audit Activity',
    description: 'Voids, refunds, inventory adjustments, and cash adjustments from immutable logs',
    category: 'audit',
    module: 'Audit',
    version: '1.0',
    status: 'active',
    purpose: 'Provide a direct, non-cached audit trail for sensitive operational events.',
    targetUsers: ['Owner', 'Manager', 'Auditor'],
    businessQuestions: ['What was voided or refunded?', 'Who changed stock or cash?', 'When did the event happen?'],
    metrics: ['void_count', 'refund_amount', 'inventory_adjustments', 'cash_adjustments'],
    dataSources: ['sales', 'returns', 'inventory_movements', 'cash_movements', 'audit_logs'],
    requiredModules: ['audit'],
    requiredCapabilities: ['reports:read', 'audit:read'],
    allowedBusinessProfiles: ['retail', 'food_service', 'hybrid'],
    availableFilters: ['dateRange', 'branchId', 'employeeId', 'eventType'],
    availableGroupings: ['eventType', 'employee', 'day', 'branch'],
    availableSorting: ['latest', 'oldest', 'highestValue'],
    supportedCharts: ['kpi', 'bar', 'table', 'timeline'],
    supportedExports: ['pdf', 'xlsx', 'csv'],
    drillDownPath: ['Audit Activity', 'Event Type', 'Source Record'],
    refreshStrategy: 'real_time',
    sensitiveFields: ['variance', 'refundAmount'],
    defaultDateRange: '30d',
  },
];
